services:
  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./ops/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports: ["9090:9090"]

  alertmanager:
    image: prom/alertmanager:v0.27.0
    volumes:
      - ./ops/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports: ["9093:9093"]
