name: build-multiarch

on:
  push:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./gollm-mini
          file: ./gollm-mini/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/gollm-backend:${{ github.sha }}
            ghcr.io/${{ github.repository }}/gollm-backend:latest
          platforms: linux/amd64,linux/arm64

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./gollm-ui
          file: ./gollm-ui/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/gollm-frontend:${{ github.sha }}
            ghcr.io/${{ github.repository }}/gollm-frontend:latest
          platforms: linux/amd64,linux/arm64
